traffichistory:
  tms:
    csv-files-url: 'http://localhost:3333/file/'
  gcloud:
    datastore:
      auth: 'none'
      host: 'http://host.docker.internal:8000'

quarkus:
  log:
    category:
      "net.mtuomiko":
        level: DEBUG
