traffichistory:
  config:
    earliest-date: '2000-01-01'
    current-date-buffer: 5
  tms:
    csv-files-url: 'https://tie.digitraffic.fi/api/tms/v1/history/raw/'
  gcloud:
    project-id: 'traffic-history-376700'
    datastore:
      auth: 'default'
      host: ''

quarkus:
  rest-client:
    tms-csv-api:
      url: '${traffichistory.tms.csv-files-url}'
  http:
    # Serve health endpoint under same path
    non-application-root-path: ${quarkus.http.root-path}
