traffichistory:
  tms:
    csv-files-url: 'http://localhost:3333/file/'
    station-api-url: 'http://localhost:3333/stations'
  gcloud:
    datastore:
      auth: 'none'
      host: 'http://host.docker.internal:8000'
