traffichistory:
  tms:
    csv-files-url: 'https://tie.digitraffic.fi/api/tms/v1/history/raw/'
    station-api-url: 'https://tie.digitraffic.fi/api/tms/v1/stations'
  gcloud:
    project-id: 'traffic-history-376700'
    datastore:
      auth: 'default'
      host: ''

quarkus:
  rest-client:
    tms-csv-api:
      url: '${traffichistory.tms.csv-files-url}'
#    tms-station-api:
#      url: '${traffichistory.tms.csv-files-url}'
#    scope: javax.inject.Singleton
  http:
    # root-path: '/api'
    # Serve health endpoint under same path
    non-application-root-path: ${quarkus.http.root-path}
