openapi: 3.0.3
info:
  title: Traffic History API
  description: |-
    Traffic History OpenAPI 3.0 specification.
  version: 0.0.1a
servers:
  - url: /
tags:
  - name: station
    description: Traffic measuring station and station traffic volume data
paths:
  /station:
    get:
      tags: [ station ]
      summary: Get all stations
      description: List stations
      operationId: getAllStations
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StationsResponse'

#  /station/{stationId}:
#    get:
#      tags: [ station ]
#      summary: Get hourly traffic volume on single station
#      description: |-
#        Returns single station hourly traffic volumes on selected days. Can select maximum 7 days on single request.
#      operationId: getStationTraffic

components:
  schemas:
    StationsResponse:
      type: object
      properties:
        stations:
          type: array
          items:
            $ref: '#/components/schemas/Station'
    Station:
      type: object
      properties:
        name:
          type: string
        tmsNumber:
          type: integer
          format: int32
        latitude:
          type: number
          format: double
        longitude:
          type: number
          format: double
