openapi: 3.0.3
info:
  title: Traffic History API
  description: |-
    Traffic History OpenAPI 3.0 specification.
  version: 0.0.1a
servers:
  - url: /
tags:
  - name: station
    description: Traffic measuring station and station traffic volume data
paths:
  /station:
    get:
      tags: [ station ]
      summary: Get all stations
      description: List stations
      operationId: getAllStations
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StationsResponse'

  /station/{stationId}:
    get:
      tags: [ station ]
      summary: Get hourly traffic volumes on single station
      description: |-
        Returns single station hourly traffic volumes on selected days. Can select maximum 7 days on single request.
      operationId: getStationTraffic
      parameters:
        - name: stationId
          in: path
          description: Station ID
          required: true
          schema:
            type: integer
            format: int32
        - name: firstDate
          in: query
          description: First date to include
          required: true
          schema:
            $ref: '#/components/schemas/DateString'
        - name: lastDate
          in: query
          description: Last date to include
          required: true
          schema:
            $ref: '#/components/schemas/DateString'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StationsResponse'

components:
  schemas:
    StationsResponse:
      type: object
      properties:
        stations:
          type: array
          items:
            $ref: '#/components/schemas/Station'
    Station:
      type: object
      properties:
        name:
          type: string
        tmsId:
          type: integer
          format: int32
        tmsNumber:
          type: integer
          format: int32
        latitude:
          type: number
          format: double
        longitude:
          type: number
          format: double
    TrafficVolumeResponse:
      type: object
      properties:
        trafficVolumes:
          type: array
          items:
            $ref: '#/components/schemas/SingleDayTrafficVolume'
    SingleDayTrafficVolume:
      type: object
      properties:
        date:
          $ref: DateString
        hourlyVolumes:
          type: array
          items:
            type: integer
            format: int32
    DateString:
      type: string
      format: date
      example: '2022-04-18'
